### ISSUE TITLE
All activities on edited after the next button has been clicked are made public

### ISSUE THREAD

**Issue by MGHollander** [jm-shi/Strava-Bulk-Editing#2]
All activities on edited after the next button has been clicked are made public, because the privacy setting is not set in the timeout.

https://github.com/jm-shi/Strava-Bulk-Editing/blob/9ed5a141112e1822faf2bf2a29ed3893a7bb5f60/strava.js#L24

Should be

`setTimeout(bulkEdit, 5000, privacySetting);`

**Comment by jm-shi** [comment]
Thanks for pointing that out. Your fix has been merged.
